### ISSUE TITLE
CloudBaseError [AUTH_FAILED]: MissingPluginException(No implementation found for method wxauth.register on channel cloudbase_auth)

### ISSUE THREAD

**Issue by meson-larry** [mingsnx/cloudbase_null_safety#1]
rt

**Comment by mingsnx** [comment]
收到，晚上回去看看解决一下

**Comment by mingsnx** [comment]
@meson-larry hello，已经将官方的插件包迁移进，但由于没有测试环境，暂时无法测试，可以更新至新的版本[1.0.5](https://pub.flutter-io.cn/packages/cloudbase_null_safety)进行试用，如若还有问题，可以再提出来

**Comment by mingsnx** [comment]
此问题暂时关闭。如有需求，可以再打开。

**Comment by hedali** [comment]
更新了1.0.5版本，这个问题还存在 @mingsnx

**Comment by mingsnx** [comment]
> 更新了1.0.5版本，这个问题还存在@mingsnx
thanks
收到 ，明天我测试一下。
这里说明一下，主要是微信登录授权有调用到原生模块，之前由于在发布包的时候完全没有集成过原生代码，所以导致此功能暂时无法使用，我会想办法测试一下，然后提交到下一个版本，有需要的可以暂时使用其他的登录方式调用，如匿名和自定义。

**Comment by mingsnx** [comment]
已通过测试✔️，解决平台插件异常问题，稍后会在下一个版本发布版本[1.1.0](https://pub.flutter-io.cn/packages/cloudbase_null_safety/versions/1.1.0)

**Comment by hedali** [comment]
> 已通过测试✔️，解决平台插件异常问题，稍后会在下一个版本发布版本[1.1.0](https://pub.flutter-io.cn/packages/cloudbase_null_safety/versions/1.1.0)

iOS端测试报：[!] No podspec found for `cloudbase_null_safety` in `.symlinks/plugins/cloudbase_null_safety/ios`

**Comment by mingsnx** [comment]
> > 已通过测试✔️，解决平台插件异常问题，稍后会在下一个版本发布版本[1.1.0](https://pub.flutter-io.cn/packages/cloudbase_null_safety/versions/1.1.0)
> 
> iOS端测试报：[!] No podspec found for `cloudbase_null_safety` in `.symlinks/plugins/cloudbase_null_safety/ios`

ok，昨天没有mac测试ios以为可以了, 待会看下

**Comment by mingsnx** [comment]
> [!] No podspec found for cloudbase_null_safety in .symlinks/plugins/cloudbase_null_safety/ios
✔️ 已解决
将在 [1.1.1](https://pub.flutter-io.cn/packages/cloudbase_null_safety/versions/1.1.1) 发布

**Comment by mingsnx** [comment]
[pub 1.1.1](https://pub.flutter-io.cn/packages/cloudbase_null_safety/versions/1.1.1) 已发布
