### ISSUE TITLE
您确定适配了空安全了吗 ？ 

### ISSUE THREAD

**Issue by peter100u** [mingsnx/cloudbase_null_safety#3]
还是报错空安全呢

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
#0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
#3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:49)
#4      MethodChannelSharedPreferencesStore.getAll (package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:44:25)
#5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:180:57)
#6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:56:19)
#7      CloudBaseStore.init (package:cloudbase_null_safety/cloudbase_core/store.dart:16:38)
#8      AuthCache.getStore (package:cloudbase_null_safety/cloudbase_auth/cache.dart:52:3<…>

**Comment by mingsnx** [comment]
最近有些忙，稍后看下再修改发布，感谢提交问题🚥

**Comment by peter100u** [comment]
感谢回复，支持大佬

> 最近有些忙，稍后看下再修改发布，感谢提交问题🚥

🙏谢谢

**Comment by mingsnx** [comment]
首先我看了一下错误的源头好像是由 `shared_preferences` 获取实例引起的，也就是在异常情况下，`getInstance`任然会返回 `null`
``` dart
// shared_preferences 包的内部实现
static Future<SharedPreferences> getInstance() async {
    if (_completer == null) {
      final completer = Completer<SharedPreferences>();
      try {
        final Map<String, Object> preferencesMap =
            await _getSharedPreferencesMap();
        completer.complete(SharedPreferences._(preferencesMap)); // 正常情况是这样返回
      } on Exception catch (e) {
        // If there's an error, explicitly return the future with an error.
        // then set the completer to null so we can retry.
        completer.completeError(e);
        // - - 当发生异常的时候，直接返回了 completer.future , 该 future 其实是空的 - -
        final Future<SharedPreferences> sharedPrefsFuture = completer.future;
        _completer = null;
        return sharedPrefsFuture;
      }
      _completer = completer;
    }
    return _completer!.future;
  }
```
再加上我对 `CloudBaseStore`对象的空安全修改为，所以 `_prefs` 字段本不改为空的，但由于 `shared_preferences`的错误导致了不正常的行为 
``` dart
class CloudBaseStore {
  // 不能为空的 SharedPreferences 对象
  late SharedPreferences _prefs;

  /// 初始化 CloudBaseStore
  Future<CloudBaseStore> init() async {
    _prefs = await SharedPreferences.getInstance(); // 所以当赋值空对象的时候，会直接报错
    return this;
  }

  ...
}
```
正常情况，这里不应该有此错误⚠️，理论上来讲，当 `shared_preferences` 不可用时，就无法正常使用腾讯云，除非我更换成`hive`来替代它的实现
所以，我就算做处理也只能做重试或也向外抛出同样的`null`异常，然后自己进行重试
请兄嘚先做以下尝试
1. 清理一下`flutter clean`再运行
2. 换个设备试试

**Comment by peter100u** [comment]
> 首先我看了一下错误的源头好像是由 `shared_preferences` 获取实例引起的，也就是在异常情况下，`getInstance`任然会返回 `null`
> 
> ```dart
> // shared_preferences 包的内部实现
> static Future<SharedPreferences> getInstance() async {
>     if (_completer == null) {
>       final completer = Completer<SharedPreferences>();
>       try {
>         final Map<String, Object> preferencesMap =
>             await _getSharedPreferencesMap();
>         completer.complete(SharedPreferences._(preferencesMap)); // 正常情况是这样返回
>       } on Exception catch (e) {
>         // If there's an error, explicitly return the future with an error.
>         // then set the completer to null so we can retry.
>         completer.completeError(e);
>         // - - 当发生异常的时候，直接返回了 completer.future , 该 future 其实是空的 - -
>         final Future<SharedPreferences> sharedPrefsFuture = completer.future;
>         _completer = null;
>         return sharedPrefsFuture;
>       }
>       _completer = completer;
>     }
>     return _completer!.future;
>   }
> ```
> 
> 再加上我对 `CloudBaseStore`对象的空安全修改为，所以 `_prefs` 字段本不改为空的，但由于 `shared_preferences`的错误导致了不正常的行为
> 
> ```dart
> class CloudBaseStore {
>   // 不能为空的 SharedPreferences 对象
>   late SharedPreferences _prefs;
> 
>   /// 初始化 CloudBaseStore
>   Future<CloudBaseStore> init() async {
>     _prefs = await SharedPreferences.getInstance(); // 所以当赋值空对象的时候，会直接报错
>     return this;
>   }
> 
>   ...
> }
> ```
> 
> 正常情况，这里不应该有此错误⚠️，理论上来讲，当 `shared_preferences` 不可用时，就无法正常使用腾讯云，除非我更换成`hive`来替代它的实现
> 所以，我就算做处理也只能做重试或也向外抛出同样的`null`异常，然后自己进行重试
> 请兄嘚先做以下尝试
> 
> 1. 清理一下`flutter clean`再运行
> 2. 换个设备试试

我已经试了，没用，卸载和换设备，都不行，还是报错，难道是初始化sp的问题或者我初始化cloud的问题吗，不应该呢，重现100%

**Comment by mingsnx** [comment]
我测试没有问题呢
**测试代码：**
``` dart
// 测试代码
final CloudBaseStore cbs = await CloudBaseStore().init();
final bool setOk = await cbs.set("-天气-", "今天是晴天");
final String value = await cbs.get("-天气-");
print("set key【-天气-】: ${setOk ? "成功" : "失败"}");
assert(setOk);
print("CloudBaseStore【-天气-】: $value");
```
**输出如下：**
![debug-cbs](https://user-images.githubusercontent.com/39380183/131293332-9271f314-99d1-41ba-83e5-41d6d891c4f4.png)

**Comment by peter100u** [comment]
> 我测试没有问题呢
> **测试代码：**
> 
> ```dart
> // 测试代码
> final CloudBaseStore cbs = await CloudBaseStore().init();
> final bool setOk = await cbs.set("-天气-", "今天是晴天");
> final String value = await cbs.get("-天气-");
> print("set key【-天气-】: ${setOk ? "成功" : "失败"}");
> assert(setOk);
> print("CloudBaseStore【-天气-】: $value");
> ```
> 
> **输出如下：**
> ![debug-cbs](https://user-images.githubusercontent.com/39380183/131293332-9271f314-99d1-41ba-83e5-41d6d891c4f4.png)

不会吧,可以把demo源码发我看下嘛

**Comment by mingsnx** [comment]
稍等一下，我这是在我项目随便写的

**Comment by mingsnx** [comment]
试一下在main中第一行加上这个
```
WidgetsFlutterBinding.ensureInitialized();
```

**Comment by mingsnx** [comment]
**demo:**
``` dart
void main() async{
  print('启动...');
  WidgetsFlutterBinding.ensureInitialized();  // 如果没有这行，会出现你的错误
  final CloudBaseStore cbs = await CloudBaseStore().init();
  final bool setOk = await cbs.set("-天气-", "今天是晴天");
  final String value = await cbs.get("-天气-");
  print("set key【-天气-】: ${setOk ? "成功" : "失败"}");
  assert(setOk);
  print("CloudBaseStore【-天气-】: $value");
}
```
**加上正常**
![image](https://user-images.githubusercontent.com/39380183/131295412-7bdc937f-a972-4d97-8931-ab62fae859ff.png)
**没加错误**
![image](https://user-images.githubusercontent.com/39380183/131295519-bc5c7c43-0327-4027-9497-5610ede40e4a.png)

**Comment by peter100u** [comment]
> **demo:**
> 
> ```dart
> void main() async{
>   print('启动...');
>   WidgetsFlutterBinding.ensureInitialized();  // 如果没有这行，会出现你的错误
>   final CloudBaseStore cbs = await CloudBaseStore().init();
>   final bool setOk = await cbs.set("-天气-", "今天是晴天");
>   final String value = await cbs.get("-天气-");
>   print("set key【-天气-】: ${setOk ? "成功" : "失败"}");
>   assert(setOk);
>   print("CloudBaseStore【-天气-】: $value");
> }
> ```
> 
> **加上正常**
> ![image](https://user-images.githubusercontent.com/39380183/131295412-7bdc937f-a972-4d97-8931-ab62fae859ff.png)
> **没加错误**
> ![image](https://user-images.githubusercontent.com/39380183/131295519-bc5c7c43-0327-4027-9497-5610ede40e4a.png)

还真是这问题，感觉大佬，耐心解决

**Comment by mingsnx** [comment]
解决就好。那这个就关闭了。

**Comment by peter100u** [comment]
> 解决就好。那这个就关闭了。

好的，好的，感谢
