### ISSUE TITLE
cloudbase_database 何时能迁移呢

### ISSUE THREAD

**Issue by Kurt-Yu** [mingsnx/cloudbase_null_safety#5]

**Comment by mingsnx** [comment]
[v1.1.2 `cloudbase_database` 迁移完成](https://pub.flutter-io.cn/packages/cloudbase_null_safety/versions/1.1.2)

**Comment by mingsnx** [comment]
这里有官方的全部单元测试例子：[官方 cloudbase_database 单元测试用例](https://github.com/mingsnx/cloudbase_null_safety/blob/master/example/lib/main.dart)

**Comment by Kurt-Yu** [comment]
> [v1.1.2 `cloudbase_database` 迁移完成](https://pub.flutter-io.cn/packages/cloudbase_null_safety/versions/1.1.2)

感谢！
