### ISSUE TITLE
无法在Android模拟器上启动调试

### ISSUE THREAD

**Issue by tokage** [mingsnx/cloudbase_null_safety#7]
编译时出现错误：
---
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.tencent.mm.opensdk:wechat-sdk-android-without-mta:+.
     Required by:
         project :app > project :cloudbase_null_safety
      > Failed to list versions for com.tencent.mm.opensdk:wechat-sdk-android-without-mta.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/tencent/mm/opensdk/wechat-sdk-android-without-mta/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/tencent/mm/opensdk/wechat-sdk-android-without-mta/maven-metadata.xml'.
               > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 35s
---
flutter --version 3.3.6

**Comment by tokage** [comment]
仓库由jcenter修改为maven center后解决，请合并PR。谢谢。

**Comment by mingsnx** [comment]
已合并。
